exports.playerData = {
	id: 1,
	name: "Arthur Morais 🚀",
	level: 42,
	health: 85,
	energy: 70,
	xp: 75,
	stats: {
		strength: 42,
		agility: 68,
		intelligence: 36,
		luck: 47,
	},
	maxSlots: 16,
	enabledSlots: 13,
	inventory: [
		{ id: 1, name: "Poção", icon: "🧪", quantity: 5, type: "potion" },
		{ id: 2, name: "Espada", icon: "⚔️", quantity: 1, type: "weapon" },
		{ id: 3, name: "Escudo", icon: "🛡️", quantity: 1, type: "armor" },
		{ id: 4, name: "Moedas", icon: "💰", quantity: 247, type: "gold" },
		{ id: 5, name: "Arco", icon: "🏹", quantity: 1, type: "weapon" },
		{
			id: 6,
			name: "Flechas do Cupido",
			icon: "💘",
			quantity: 20,
			type: "ammo",
		},
		{ id: 7, name: "Elixir", icon: "🍷", quantity: 3, type: "potion" },
		{ id: 8, name: "Pergaminho", icon: "📜", quantity: 2, type: "scroll" },
	],
};
